In [1]:
import numpy as np

a = np.random.rand(5) #a.shape = (5,)

print(a) # rank 1 array

[0.99502822 0.44683727 0.86134759 0.1150056  0.03489082]


In [2]:
print(a.shape)

(5,)


In [3]:
print(a.T) # transpose

[0.99502822 0.44683727 0.86134759 0.1150056  0.03489082]


In [4]:
print(np.dot(a,a.T))

1.9461080241039632


In [5]:
a = np.random.rand(5,1)
print(a)

[[0.10949663]
 [0.15521517]
 [0.45470462]
 [0.95001735]
 [0.63682726]]


In [6]:
print(a.T)

[[0.10949663 0.15521517 0.45470462 0.95001735 0.63682726]]


In [7]:
print(np.dot(a,a.T))

[[0.01198951 0.01699554 0.04978862 0.1040237  0.06973044]
 [0.01699554 0.02409175 0.07057705 0.1474571  0.09884525]
 [0.04978862 0.07057705 0.20675629 0.43197727 0.28956829]
 [0.1040237  0.1474571  0.43197727 0.90253296 0.60499694]
 [0.06973044 0.09884525 0.28956829 0.60499694 0.40554896]]
